### ISSUE TITLE
Adobe Creative Cloud

### ISSUE THREAD

**Issue by foggjd** [StatusTicker/statusticker-support#155]
https://status.adobe.com/

**Comment by hotmeteor** [comment]
We have:

https://statusticker.com/s/Adobe-Behance
https://statusticker.com/s/Adobe-Lightroom
https://statusticker.com/s/Adobe-Magento
https://statusticker.com/s/Adobe-Marketo-Engage
https://statusticker.com/s/Adobe-Photoshop
https://statusticker.com/s/Adobe-Sign

Is there a particular service you're looking for?

**Comment by foggjd** [comment]
Creative Cloud Sharing and Commenting, Creative Cloud Storage, Creative Cloud Sync, and InDesign would be super helpful!

**Comment by hotmeteor** [comment]
Added, should be live and tracking shortly.
