### ISSUE TITLE
Feature request: dismiss an issue

### ISSUE THREAD

**Issue by jkudish** [StatusTicker/statusticker-support#59]
Would be pretty neat if I could dismiss a specific issue.

For example here are two issue I don't really care about:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/260253/33498423-20f9adba-d686-11e7-9276-4f91ed39a911.png">

Would be cool if I could dismiss them so it shows that service as green again

**Comment by hotmeteor** [comment]
@jkudish The ability to "mute" a service is now available.

By muting a service it will move it to the bottom of your list and remove all specific status coloring. Once the status changes it will automatically be unmuted. Of course, you can unmute it manually at any time.
